services:
  postgres:
    image: postgres:16
    container_name: score-db
    restart: always
    environment:
      POSTGRES_DB: scoredb
      POSTGRES_USER: scoreuser
      POSTGRES_PASSWORD: scorepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  score-app:
    build:
      dockerfile: Dockerfile
    container_name: score-api
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/scoredb
      SPRING_DATASOURCE_USERNAME: scoreuser
      SPRING_DATASOURCE_PASSWORD: scorepass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  postgres_data: