# Spring Boot configuration
server:
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: ${KEY_STORE_FILE_VALUE}
    key-store-password: ${KEY_STORE_PASSWORD_VALUE}
    key-store-type: ${KEY_STORE_TYPE}
  port: 8282
spring:
  config:
    import: env.properties
  profiles:
    active: dev
  application:
    name: loan
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_DATABASE_HOST}:5432/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}:${BOOTSTRAP_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: loan-contract-accept
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  cache:
    type: ${CACHE_TYPE:redis}
    redis:
      time-to-live: 100000
topic:
  name:
    producer: loan-contract-accept
api:
  availability:
    url: ${AVAILABILITY_API:https://localhost:8080/restriction}
    name: availability
  score:
    url: ${SCORE_API:https://localhost:8080/score}
    name: score